
const EspToRUsVerbs = [
    { "infinitive": "abandonar", "verb_russian": "оставить (бросить)", "type_of_verb": "regular" },
    { "infinitive": "abordar", "verb_russian": "приступать, сталкиваться, обратиться", "type_of_verb": "regular" },
    { "infinitive": "abortar", "verb_russian": "сорваться, прерваться, отмениться", "type_of_verb": "regular" },
    { "infinitive": "abrazar", "verb_russian": "обнимать", "type_of_verb": "regular" },
    { "infinitive": "abrir", "verb_russian": "открывать", "type_of_verb": "irregular" },
    { "infinitive": "aburrir", "verb_russian": "надоедать", "type_of_verb": "regular" },
    { "infinitive": "aburrirse", "verb_russian": "скучать, соскучиться, томиться", "type_of_verb": "regular" },
    { "infinitive": "abusar", "verb_russian": "злоупотребялть", "type_of_verb": "regular" },
    { "infinitive": "acabar", "verb_russian": "заканчивать (кончаться)", "type_of_verb": "regular" },
    { "infinitive": "acampar", "verb_russian": "разбить лагерь", "type_of_verb": "regular" },
    { "infinitive": "aceptar", "verb_russian": "принимать", "type_of_verb": "regular" },
    { "infinitive": "acercar", "verb_russian": "приближать, объединять", "type_of_verb": "regular" },
    { "infinitive": "acercarse", "verb_russian": "приближаться", "type_of_verb": "regular" },
    { "infinitive": "acompañar", "verb_russian": "сопровождать", "type_of_verb": "regular" },
    { "infinitive": "aconsejar", "verb_russian": "советовать", "type_of_verb": "regular" },
    { "infinitive": "acontecer", "verb_russian": "случиться, произойти", "type_of_verb": "irregular" },
    { "infinitive": "acordar", "verb_russian": "договориться", "type_of_verb": "irregular" },
    { "infinitive": "acordarse", "verb_russian": "вспоминать (помнить)", "type_of_verb": "irregular" },
    { "infinitive": "acortar", "verb_russian": "сократить, уменьшить", "type_of_verb": "regular" },
    { "infinitive": "acostar", "verb_russian": "положить, класть", "type_of_verb": "irregular" },
    { "infinitive": "acostarse", "verb_russian": "ложиться спать", "type_of_verb": "irregular" },
    { "infinitive": "acostumbrar", "verb_russian": "приучать", "type_of_verb": "regular" },
    { "infinitive": "acostumbrarse", "verb_russian": "приучаться, привыкать, свыкнуться", "type_of_verb": "regular" },
    { "infinitive": "actuar", "verb_russian": "действовать", "type_of_verb": "regular" },
    { "infinitive": "adivinar", "verb_russian": "угадывать, догадываться", "type_of_verb": "regular" },
    { "infinitive": "admirar", "verb_russian": "восхищаться", "type_of_verb": "regular" },
    { "infinitive": "admitir", "verb_russian": "признавать (принимать)", "type_of_verb": "regular" },
    { "infinitive": "adorar", "verb_russian": "обожать", "type_of_verb": "regular" },
    { "infinitive": "adornar", "verb_russian": "украшать", "type_of_verb": "regular" },
    { "infinitive": "advertir", "verb_russian": "замечать", "type_of_verb": "irregular" },
    { "infinitive": "afeitar", "verb_russian": "брить", "type_of_verb": "regular" },
    { "infinitive": "afeitarse", "verb_russian": "бриться", "type_of_verb": "regular" },
    { "infinitive": "afirmar", "verb_russian": "утверждать", "type_of_verb": "regular" },
    { "infinitive": "afligir", "verb_russian": "огорчать", "type_of_verb": "regular" },
    { "infinitive": "agorar", "verb_russian": "предвещать", "type_of_verb": "irregular" },
    { "infinitive": "agradar", "verb_russian": "нравиться, быть приятным", "type_of_verb": "regular" },
    { "infinitive": "agradecer", "verb_russian": "благодарить", "type_of_verb": "irregular" },
    { "infinitive": "aguantar", "verb_russian": "держать (терпеть)", "type_of_verb": "regular" },
    { "infinitive": "ahorcar", "verb_russian": "вешать", "type_of_verb": "regular" },
    { "infinitive": "ahorrar", "verb_russian": "экономить (беречь)", "type_of_verb": "regular" },
    { "infinitive": "alcanzar", "verb_russian": "достигать", "type_of_verb": "regular" },
    { "infinitive": "alegrar", "verb_russian": "радовать", "type_of_verb": "regular" },
    { "infinitive": "alegrarse", "verb_russian": "радоваться", "type_of_verb": "regular" },
    { "infinitive": "alentar", "verb_russian": "воодушевлять", "type_of_verb": "irregular" },
    { "infinitive": "aliviar", "verb_russian": "облегчить", "type_of_verb": "regular" },
    { "infinitive": "almorzar", "verb_russian": "обедать (завтракать)", "type_of_verb": "irregular" },
    { "infinitive": "alquilar", "verb_russian": "арендовать", "type_of_verb": "regular" },
    { "infinitive": "amanecer", "verb_russian": "рассветать", "type_of_verb": "irregular" },
    { "infinitive": "amar", "verb_russian": "любить", "type_of_verb": "regular" },
    { "infinitive": "amenazar", "verb_russian": "угрожать", "type_of_verb": "regular" },
    { "infinitive": "añadir", "verb_russian": "добавлять", "type_of_verb": "regular" },
    { "infinitive": "andar", "verb_russian": "ходить", "type_of_verb": "irregular" },
    { "infinitive": "anhelar", "verb_russian": "жаждать, желать", "type_of_verb": "regular" },
    { "infinitive": "anunciar", "verb_russian": "объявить", "type_of_verb": "regular" },
    { "infinitive": "apagar", "verb_russian": "выключать (погасить)", "type_of_verb": "regular" },
    { "infinitive": "aparecer", "verb_russian": "появляться", "type_of_verb": "irregular" },
    { "infinitive": "aplaudir", "verb_russian": "аплодировать", "type_of_verb": "regular" },
    { "infinitive": "aplicar", "verb_russian": "применять, использовать", "type_of_verb": "regular" },
    { "infinitive": "apostar", "verb_russian": "держать пари, делать ставку", "type_of_verb": "irregular" },
    { "infinitive": "apoyar", "verb_russian": "поддерживать, опираться", "type_of_verb": "regular" },
    { "infinitive": "apreciar", "verb_russian": "ценить", "type_of_verb": "regular" },
    { "infinitive": "aprender", "verb_russian": "изучать", "type_of_verb": "regular" },
    { "infinitive": "apretar", "verb_russian": "затягивать, прижимать", "type_of_verb": "irregular" },
    { "infinitive": "aprobar", "verb_russian": "сдать экзамен", "type_of_verb": "irregular" },
    { "infinitive": "arreglar", "verb_russian": "чинить", "type_of_verb": "regular" },
    { "infinitive": "arrepentirse", "verb_russian": "раскаиваться", "type_of_verb": "irregular" },
    { "infinitive": "arrojar", "verb_russian": "бросать", "type_of_verb": "regular" },
    { "infinitive": "asistir", "verb_russian": "присутствовать", "type_of_verb": "regular" },
    { "infinitive": "asociar", "verb_russian": "ассоциировать", "type_of_verb": "regular" },
    { "infinitive": "aspirar", "verb_russian": "стремиться", "type_of_verb": "regular" },
    { "infinitive": "asustar", "verb_russian": "пугать", "type_of_verb": "regular" },
    { "infinitive": "asustarse", "verb_russian": "пугаться", "type_of_verb": "regular" },
    { "infinitive": "atacar", "verb_russian": "атаковать", "type_of_verb": "regular" },
    { "infinitive": "atender", "verb_russian": "уделять внимание", "type_of_verb": "irregular" },
    { "infinitive": "atraer", "verb_russian": "привлекать", "type_of_verb": "irregular" },
    { "infinitive": "atravesar", "verb_russian": "пересекать", "type_of_verb": "irregular" },
    { "infinitive": "atreverse", "verb_russian": "осмелиться", "type_of_verb": "regular" },
    { "infinitive": "aumentar", "verb_russian": "увеличивать", "type_of_verb": "regular" },
    { "infinitive": "avanzar", "verb_russian": "продвигаться, двигать вперед", "type_of_verb": "regular" },
    { "infinitive": "averiguar", "verb_russian": "выяснить", "type_of_verb": "regular" },
    { "infinitive": "avisar", "verb_russian": "предупреждать", "type_of_verb": "regular" },
    { "infinitive": "ayudar", "verb_russian": "помогать", "type_of_verb": "regular" },
    { "infinitive": "bailar", "verb_russian": "танцевать", "type_of_verb": "regular" },
    { "infinitive": "bajar", "verb_russian": "спускаться (падать)", "type_of_verb": "regular" },
    { "infinitive": "bañar", "verb_russian": "купать, мыть", "type_of_verb": "regular" },
    { "infinitive": "bañarse", "verb_russian": "купаться, принимать ванну", "type_of_verb": "regular" },
    { "infinitive": "barrer", "verb_russian": "мести, подметать", "type_of_verb": "regular" },
    { "infinitive": "batir", "verb_russian": "бить, ударять", "type_of_verb": "regular" },
    { "infinitive": "bautizar", "verb_russian": "крестить, окрестить, называть", "type_of_verb": "regular" },
    { "infinitive": "beber", "verb_russian": "пить", "type_of_verb": "regular" },
    { "infinitive": "bendecir", "verb_russian": "благославлять, освещать", "type_of_verb": "irregular" },
    { "infinitive": "besar", "verb_russian": "целовать", "type_of_verb": "regular" },
    { "infinitive": "bordar", "verb_russian": "шить, вышивать", "type_of_verb": "regular" },
    { "infinitive": "borrar", "verb_russian": "стереть, сбросить, удалить", "type_of_verb": "regular" },
    { "infinitive": "brillar", "verb_russian": "блестеть (сверкать)", "type_of_verb": "regular" },
    { "infinitive": "brindar", "verb_russian": "оказывать", "type_of_verb": "regular" },
    { "infinitive": "broncearse", "verb_russian": "загорать", "type_of_verb": "regular" },
    { "infinitive": "bucear", "verb_russian": "нырять", "type_of_verb": "regular" },
    { "infinitive": "burlar", "verb_russian": "перехитрить, несмехаться", "type_of_verb": "regular" },
    { "infinitive": "burlarse", "verb_russian": "насмехаться, глумиться издеваться", "type_of_verb": "regular" },
    { "infinitive": "buscar", "verb_russian": "искать", "type_of_verb": "regular" },
    { "infinitive": "caber", "verb_russian": "вмещать", "type_of_verb": "irregular" },
    { "infinitive": "caer", "verb_russian": "падать", "type_of_verb": "irregular" },
    { "infinitive": "calcular", "verb_russian": "вычислять, рассчитать", "type_of_verb": "regular" },
    { "infinitive": "calentar", "verb_russian": "нагревать, согреть", "type_of_verb": "irregular" },
    { "infinitive": "calentarse", "verb_russian": "греться, согреваться", "type_of_verb": "irregular" },
    { "infinitive": "callar", "verb_russian": "молчать", "type_of_verb": "regular" },
    { "infinitive": "callarse", "verb_russian": "умолкнуть", "type_of_verb": "regular" },
    { "infinitive": "calmar", "verb_russian": "успокаивать", "type_of_verb": "regular" },
    { "infinitive": "calmarse", "verb_russian": "успокоиться, затихнуть", "type_of_verb": "regular" },
    { "infinitive": "caminar", "verb_russian": "ходить", "type_of_verb": "regular" },
    { "infinitive": "cancelar", "verb_russian": "отменить, аннулировать", "type_of_verb": "regular" },
    { "infinitive": "cansar", "verb_russian": "уставать, утомлять, надоедать", "type_of_verb": "regular" },
    { "infinitive": "cansarse", "verb_russian": "утомиться, утомляться", "type_of_verb": "regular" },
    { "infinitive": "caracterizar", "verb_russian": "охарактеризовать, описать", "type_of_verb": "regular" },
    { "infinitive": "cargar", "verb_russian": "загрузить, загружать, заряжать", "type_of_verb": "regular" },
    { "infinitive": "casar", "verb_russian": "жениться", "type_of_verb": "regular" },
    { "infinitive": "casarse", "verb_russian": "выйти замуж, жениться", "type_of_verb": "regular" },
    { "infinitive": "castigar", "verb_russian": "наказывать (мучить)", "type_of_verb": "regular" },
    { "infinitive": "causar", "verb_russian": "вызывать, принести, причинять", "type_of_verb": "regular" },
    { "infinitive": "cazar", "verb_russian": "охотиться, ловить", "type_of_verb": "regular" },
    { "infinitive": "celebrar", "verb_russian": "праздновать", "type_of_verb": "regular" },
    { "infinitive": "cenar", "verb_russian": "ужинать", "type_of_verb": "regular" },
    { "infinitive": "censurar", "verb_russian": "цензурировать", "type_of_verb": "regular" },
    { "infinitive": "cepillar", "verb_russian": "чистить", "type_of_verb": "regular" },
    { "infinitive": "cerrar", "verb_russian": "закрывать", "type_of_verb": "irregular" },
    { "infinitive": "cesar", "verb_russian": "прекратить", "type_of_verb": "regular" },
    { "infinitive": "charlar", "verb_russian": "болтать", "type_of_verb": "regular" },
    { "infinitive": "chismear", "verb_russian": "сплетничать", "type_of_verb": "regular" },
    { "infinitive": "chocar", "verb_russian": "врезаться, сталкиваться", "type_of_verb": "regular" },
    { "infinitive": "civilizar", "verb_russian": "цивилизовать", "type_of_verb": "regular" },
    { "infinitive": "clarificar", "verb_russian": "объяснить, прояснить", "type_of_verb": "regular" },
    { "infinitive": "clasificar", "verb_russian": "классифицировать, сортировать", "type_of_verb": "regular" },
    { "infinitive": "cobrar", "verb_russian": "взимать, взыскивать", "type_of_verb": "regular" },
    { "infinitive": "cocinar", "verb_russian": "готовить", "type_of_verb": "regular" },
    { "infinitive": "coger", "verb_russian": "брать (взять)", "type_of_verb": "regular" },
    { "infinitive": "colgar", "verb_russian": "повесить, висеть, положить трубку", "type_of_verb": "irregular" },
    { "infinitive": "colocar", "verb_russian": "размещать", "type_of_verb": "regular" },
    { "infinitive": "colonizar", "verb_russian": "колонизировать", "type_of_verb": "regular" },
    { "infinitive": "combatir", "verb_russian": "бороться", "type_of_verb": "regular" },
    { "infinitive": "comenzar", "verb_russian": "начинать", "type_of_verb": "irregular" },
    { "infinitive": "comer", "verb_russian": "есть (пищу)", "type_of_verb": "regular" },
    { "infinitive": "compartir", "verb_russian": "разделять", "type_of_verb": "regular" },
    { "infinitive": "competir", "verb_russian": "соревноваться", "type_of_verb": "irregular" },
    { "infinitive": "componer", "verb_russian": "составлять", "type_of_verb": "irregular" },
    { "infinitive": "comprar", "verb_russian": "покупать", "type_of_verb": "regular" },
    { "infinitive": "comprender", "verb_russian": "понимать", "type_of_verb": "regular" },
    { "infinitive": "comunicar", "verb_russian": "общаться, сообщить", "type_of_verb": "regular" },
    { "infinitive": "comunicarse", "verb_russian": "общаться", "type_of_verb": "regular" },
    { "infinitive": "condenar", "verb_russian": "осуждать", "type_of_verb": "regular" },
    { "infinitive": "conducir", "verb_russian": "водить машину", "type_of_verb": "irregular" },
    { "infinitive": "confesar", "verb_russian": "признаваться", "type_of_verb": "irregular" },
    { "infinitive": "confiar", "verb_russian": "доверять (полагаться)", "type_of_verb": "regular" },
    { "infinitive": "confirmar", "verb_russian": "подтверждать", "type_of_verb": "regular" },
    { "infinitive": "confiscar", "verb_russian": "конфисковать", "type_of_verb": "regular" },
    { "infinitive": "conjugar", "verb_russian": "спрягать, сочетать, комбинировать", "type_of_verb": "regular" },
    { "infinitive": "conocer", "verb_russian": "знать", "type_of_verb": "irregular" },
    { "infinitive": "conquistar", "verb_russian": "завоевывать", "type_of_verb": "regular" },
    { "infinitive": "conseguir", "verb_russian": "достигать", "type_of_verb": "irregular" },
    { "infinitive": "consentir", "verb_russian": "разрешать (соглашаться)", "type_of_verb": "irregular" },
    { "infinitive": "conservar", "verb_russian": "хранить", "type_of_verb": "regular" },
    { "infinitive": "consistir", "verb_russian": "состоять", "type_of_verb": "regular" },
    { "infinitive": "constituir", "verb_russian": "составлять (учреждать)", "type_of_verb": "regular" },
    { "infinitive": "construir", "verb_russian": "строить", "type_of_verb": "regular" },
    { "infinitive": "consumir", "verb_russian": "потреблять", "type_of_verb": "regular" },
    { "infinitive": "contaminar", "verb_russian": "загрязнять", "type_of_verb": "regular" },
    { "infinitive": "contar", "verb_russian": "подсчитывать", "type_of_verb": "irregular" },
    { "infinitive": "contener", "verb_russian": "содержать", "type_of_verb": "irregular" },
    { "infinitive": "contestar", "verb_russian": "отвечать", "type_of_verb": "regular" },
    { "infinitive": "continuar", "verb_russian": "продолжать", "type_of_verb": "regular" },
    { "infinitive": "contribuir", "verb_russian": "делать вклад", "type_of_verb": "regular" },
    { "infinitive": "controlar", "verb_russian": "контролировать", "type_of_verb": "regular" },
    { "infinitive": "convencer", "verb_russian": "убеждать", "type_of_verb": "regular" },
    { "infinitive": "convenir", "verb_russian": "подходить (договариваться)", "type_of_verb": "irregular" },
    { "infinitive": "conversar", "verb_russian": "разговаривать", "type_of_verb": "regular" },
    { "infinitive": "convertir", "verb_russian": "превращать", "type_of_verb": "irregular" },
    { "infinitive": "convidar", "verb_russian": "позвать", "type_of_verb": "regular" },
    { "infinitive": "copiar", "verb_russian": "копировать", "type_of_verb": "regular" },
    { "infinitive": "corregir", "verb_russian": "исправлять", "type_of_verb": "irregular" },
    { "infinitive": "correr", "verb_russian": "бегать (бежать)", "type_of_verb": "regular" },
    { "infinitive": "cortar", "verb_russian": "стричь (резать, сокращать)", "type_of_verb": "regular" },
    { "infinitive": "coser", "verb_russian": "шить", "type_of_verb": "regular" },
    { "infinitive": "costar", "verb_russian": "стоить", "type_of_verb": "irregular" },
    { "infinitive": "dar", "verb_russian": "давать", "type_of_verb": "irregular" },
    { "infinitive": "deber", "verb_russian": "быть должным", "type_of_verb": "regular" },
    { "infinitive": "decidir", "verb_russian": "решать", "type_of_verb": "regular" },
    { "infinitive": "decidirse", "verb_russian": "решиться осмелиться", "type_of_verb": "regular" },
    { "infinitive": "decir", "verb_russian": "сказать", "type_of_verb": "irregular" },
    { "infinitive": "declarar", "verb_russian": "объявить", "type_of_verb": "regular" },
    { "infinitive": "decorar", "verb_russian": "украсить", "type_of_verb": "regular" },
    { "infinitive": "dedicar", "verb_russian": "посвятить, уделить, отдавать", "type_of_verb": "regular" },
    { "infinitive": "dedicarse", "verb_russian": "заниматься, посвящать себя", "type_of_verb": "regular" },
    { "infinitive": "defender", "verb_russian": "защищать", "type_of_verb": "irregular" },
    { "infinitive": "dejar", "verb_russian": "оставлять", "type_of_verb": "regular" },
    { "infinitive": "demostrar", "verb_russian": "доказывать", "type_of_verb": "irregular" },
    { "infinitive": "depender", "verb_russian": "зависеть", "type_of_verb": "regular" },
    { "infinitive": "depositar", "verb_russian": "внести", "type_of_verb": "regular" },
    { "infinitive": "deprimir", "verb_russian": "угнетать (удручать)", "type_of_verb": "regular" },
    { "infinitive": "derretir", "verb_russian": "растопить, расплавить", "type_of_verb": "irregular" },
    { "infinitive": "desagradar", "verb_russian": "не нравиться", "type_of_verb": "regular" },
    { "infinitive": "desagradecer", "verb_russian": "быть неблагодарным", "type_of_verb": "regular" },
    { "infinitive": "desaparecer", "verb_russian": "исчезать", "type_of_verb": "irregular" },
    { "infinitive": "desarrollar", "verb_russian": "разработать, развивать, производить", "type_of_verb": "regular" },
    { "infinitive": "desarrollarse", "verb_russian": "развиваться, расти", "type_of_verb": "regular" },
    { "infinitive": "desayunar", "verb_russian": "завтракать", "type_of_verb": "regular" },
    { "infinitive": "descansar", "verb_russian": "отдыхать", "type_of_verb": "regular" },
    { "infinitive": "descender", "verb_russian": "спускаться", "type_of_verb": "irregular" },
    { "infinitive": "describir", "verb_russian": "описывать", "type_of_verb": "irregular" },
    { "infinitive": "descubrir", "verb_russian": "открыть", "type_of_verb": "regular" },
    { "infinitive": "desear", "verb_russian": "желать", "type_of_verb": "regular" },
    { "infinitive": "deshacer", "verb_russian": "разрушать", "type_of_verb": "irregular" },
    { "infinitive": "despedir", "verb_russian": "увольнять", "type_of_verb": "irregular" },
    { "infinitive": "despertar", "verb_russian": "проснуться, будить", "type_of_verb": "irregular" },
    { "infinitive": "despertarse", "verb_russian": "просыпаться", "type_of_verb": "irregular" },
    { "infinitive": "destruir", "verb_russian": "разрушать (уничтожить)", "type_of_verb": "regular" },
    { "infinitive": "detener", "verb_russian": "остановить (задержать)", "type_of_verb": "irregular" },
    { "infinitive": "detenerse", "verb_russian": "остановиться, медлить, тянуть", "type_of_verb": "irregular" },
    { "infinitive": "detestar", "verb_russian": "ненавидеть", "type_of_verb": "regular" },
    { "infinitive": "devolver", "verb_russian": "вернуть", "type_of_verb": "irregular" },
    { "infinitive": "devorar", "verb_russian": "пожирать, поедать", "type_of_verb": "regular" },
    { "infinitive": "dibujar", "verb_russian": "рисовать", "type_of_verb": "regular" },
    { "infinitive": "dirigir", "verb_russian": "направлять (руководить)", "type_of_verb": "regular" },
    { "infinitive": "diseñar", "verb_russian": "рисовать (проектировать)", "type_of_verb": "regular" },
    { "infinitive": "disfrutar", "verb_russian": "наслаждаться", "type_of_verb": "regular" },
    { "infinitive": "disgustar", "verb_russian": "не нравиться, расстроить", "type_of_verb": "regular" },
    { "infinitive": "disminuir", "verb_russian": "уменьшать", "type_of_verb": "regular" },
    { "infinitive": "distinguir", "verb_russian": "различать", "type_of_verb": "regular" },
    { "infinitive": "distribuir", "verb_russian": "распределять", "type_of_verb": "regular" },
    { "infinitive": "divertir", "verb_russian": "развлекать, веселить", "type_of_verb": "irregular" },
    { "infinitive": "divertirse", "verb_russian": "веселиться (развлекаться)", "type_of_verb": "irregular" },
    { "infinitive": "divorciar", "verb_russian": "разводить, расторгнуть брак", "type_of_verb": "regular" },
    { "infinitive": "divorciarse", "verb_russian": "разводиться (расторгать брак)", "type_of_verb": "regular" },
    { "infinitive": "doblar", "verb_russian": "удваивать", "type_of_verb": "regular" },
    { "infinitive": "doler", "verb_russian": "болеть (причинять боль)", "type_of_verb": "irregular" },
    { "infinitive": "dormir", "verb_russian": "спать", "type_of_verb": "irregular" },
    { "infinitive": "dormirse", "verb_russian": "засыпать", "type_of_verb": "irregular" },
    { "infinitive": "duchar", "verb_russian": "принимать душ, мыться", "type_of_verb": "regular" },
    { "infinitive": "ducharse", "verb_russian": "принимать душ", "type_of_verb": "regular" },
    { "infinitive": "dudar", "verb_russian": "сомневаться", "type_of_verb": "regular" },
    { "infinitive": "durar", "verb_russian": "длиться", "type_of_verb": "regular" },
    { "infinitive": "echar", "verb_russian": "выгнать", "type_of_verb": "regular" },
    { "infinitive": "echarse", "verb_russian": "броситься", "type_of_verb": "regular" },
    { "infinitive": "educar", "verb_russian": "воспитывать", "type_of_verb": "regular" },
    { "infinitive": "efectuar", "verb_russian": "делать, выполнять, осуществлять", "type_of_verb": "regular" },
    { "infinitive": "ejercer", "verb_russian": "осуществлять (исполнять)", "type_of_verb": "regular" },
    { "infinitive": "elegir", "verb_russian": "выбирать", "type_of_verb": "irregular" },
    { "infinitive": "eliminar", "verb_russian": "удалять", "type_of_verb": "regular" },
    { "infinitive": "emborrachar", "verb_russian": "пьянить, опьянять", "type_of_verb": "regular" },
    { "infinitive": "emborracharse", "verb_russian": "напиться, пьянствовать", "type_of_verb": "regular" },
    { "infinitive": "emigrar", "verb_russian": "эмигрировать", "type_of_verb": "regular" },
    { "infinitive": "empezar", "verb_russian": "начать", "type_of_verb": "irregular" },
    { "infinitive": "emplear", "verb_russian": "использовать", "type_of_verb": "regular" },
    { "infinitive": "enamorar", "verb_russian": "влюбиться", "type_of_verb": "regular" },
    { "infinitive": "enamorarse", "verb_russian": "влюбляться", "type_of_verb": "regular" },
    { "infinitive": "encantar", "verb_russian": "очень нравиться", "type_of_verb": "regular" },
    { "infinitive": "encender", "verb_russian": "включать (зажигать)", "type_of_verb": "irregular" },
    { "infinitive": "encontrar", "verb_russian": "находить", "type_of_verb": "irregular" },
    { "infinitive": "enfadar", "verb_russian": "разозлить", "type_of_verb": "regular" },
    { "infinitive": "enfadarse", "verb_russian": "злиться", "type_of_verb": "regular" },
    { "infinitive": "enfermar", "verb_russian": "заболеть", "type_of_verb": "regular" },
    { "infinitive": "enfermarse", "verb_russian": "заболеть", "type_of_verb": "regular" },
    { "infinitive": "enflaquecer", "verb_russian": "худеть", "type_of_verb": "regular" },
    { "infinitive": "enflaquecerse", "verb_russian": "похудеть", "type_of_verb": "irregular" },
    { "infinitive": "engañar", "verb_russian": "обманывать", "type_of_verb": "regular" },
    { "infinitive": "enojar", "verb_russian": "сердить", "type_of_verb": "regular" },
    { "infinitive": "enojarse", "verb_russian": "злиться", "type_of_verb": "regular" },
    { "infinitive": "enriquecer", "verb_russian": "обогащать", "type_of_verb": "irregular" },
    { "infinitive": "enriquecerse", "verb_russian": "разбогатеть", "type_of_verb": "irregular" },
    { "infinitive": "enseñar", "verb_russian": "учить", "type_of_verb": "regular" },
    { "infinitive": "ensuciar", "verb_russian": "пачкать", "type_of_verb": "regular" },
    { "infinitive": "entender", "verb_russian": "понимать (понять)", "type_of_verb": "irregular" },
    { "infinitive": "enterarse", "verb_russian": "выяснить", "type_of_verb": "regular" },
    { "infinitive": "entrar", "verb_russian": "входить", "type_of_verb": "regular" },
    { "infinitive": "entregar", "verb_russian": "доставлять", "type_of_verb": "regular" },
    { "infinitive": "entretener", "verb_russian": "развлекать", "type_of_verb": "irregular" },
    { "infinitive": "entrevistar", "verb_russian": "брать интервью", "type_of_verb": "regular" },
    { "infinitive": "entusiasmar", "verb_russian": "приводить в восторг", "type_of_verb": "regular" },
    { "infinitive": "entusiasmarse", "verb_russian": "восторгаться", "type_of_verb": "regular" },
    { "infinitive": "envejecer", "verb_russian": "стареть", "type_of_verb": "irregular" },
    { "infinitive": "envejecerse", "verb_russian": "состариться", "type_of_verb": "regular" },
    { "infinitive": "enviar", "verb_russian": "посылать (отправлять)", "type_of_verb": "regular" },
    { "infinitive": "equivocar", "verb_russian": "ошибиться", "type_of_verb": "regular" },
    { "infinitive": "equivocarse", "verb_russian": "ошибаться, делать ошибки", "type_of_verb": "regular" },
    { "infinitive": "errar", "verb_russian": "ошибаться", "type_of_verb": "irregular" },
    { "infinitive": "escoger", "verb_russian": "выбрать", "type_of_verb": "regular" },
    { "infinitive": "esconder", "verb_russian": "спрятать", "type_of_verb": "regular" },
    { "infinitive": "esconderse", "verb_russian": "прятаться", "type_of_verb": "regular" },
    { "infinitive": "escribir", "verb_russian": "писать", "type_of_verb": "irregular" },
    { "infinitive": "escuchar", "verb_russian": "слушать", "type_of_verb": "regular" },
    { "infinitive": "esperar", "verb_russian": "ждать", "type_of_verb": "regular" },
    { "infinitive": "esquiar", "verb_russian": "кататься на лыжах", "type_of_verb": "regular" },
    { "infinitive": "establecer", "verb_russian": "учреждать", "type_of_verb": "irregular" },
    { "infinitive": "estar", "verb_russian": "быть", "type_of_verb": "irregular" },
    { "infinitive": "estimar", "verb_russian": "оценивать", "type_of_verb": "regular" },
    { "infinitive": "estudiar", "verb_russian": "учиться (изучать)", "type_of_verb": "regular" },
    { "infinitive": "evacuar", "verb_russian": "эвакуироваться", "type_of_verb": "regular" },
    { "infinitive": "evitar", "verb_russian": "избегать", "type_of_verb": "regular" },
    { "infinitive": "exhibir", "verb_russian": "выставлять", "type_of_verb": "regular" },
    { "infinitive": "exigir", "verb_russian": "требовать", "type_of_verb": "regular" },
    { "infinitive": "explicar", "verb_russian": "объяснять", "type_of_verb": "regular" },
    { "infinitive": "explorar", "verb_russian": "исследовать", "type_of_verb": "regular" },
    { "infinitive": "explotar", "verb_russian": "эксплуатировать", "type_of_verb": "regular" },
    { "infinitive": "exponer", "verb_russian": "разоблачать", "type_of_verb": "irregular" },
    { "infinitive": "exportar", "verb_russian": "экспортировать", "type_of_verb": "regular" },
    { "infinitive": "expresar", "verb_russian": "выражать", "type_of_verb": "regular" },
    { "infinitive": "extender", "verb_russian": "увеличивать (расширять)", "type_of_verb": "irregular" },
    { "infinitive": "extinguir", "verb_russian": "тушить", "type_of_verb": "regular" },
    { "infinitive": "fabricar", "verb_russian": "производить, изготавливать", "type_of_verb": "regular" },
    { "infinitive": "faltar", "verb_russian": "отсутствовать", "type_of_verb": "regular" },
    { "infinitive": "fascinar", "verb_russian": "очаровывать", "type_of_verb": "regular" },
    { "infinitive": "felicitar", "verb_russian": "поздравлять", "type_of_verb": "regular" },
    { "infinitive": "fijar", "verb_russian": "фиксировать, закреплять", "type_of_verb": "regular" },
    { "infinitive": "fingir", "verb_russian": "притворяться", "type_of_verb": "regular" },
    { "infinitive": "firmar", "verb_russian": "подписывать", "type_of_verb": "regular" },
    { "infinitive": "florecer", "verb_russian": "процветать", "type_of_verb": "irregular" },
    { "infinitive": "formar", "verb_russian": "формировать", "type_of_verb": "regular" },
    { "infinitive": "fortalecer", "verb_russian": "укреплять", "type_of_verb": "irregular" },
    { "infinitive": "freír", "verb_russian": "жарить", "type_of_verb": "irregular" },
    { "infinitive": "fumar", "verb_russian": "курить", "type_of_verb": "regular" },
    { "infinitive": "funcionar", "verb_russian": "действовать (работать)", "type_of_verb": "regular" },
    { "infinitive": "ganar", "verb_russian": "выиграть (зарабатывать)", "type_of_verb": "regular" },
    { "infinitive": "gastar", "verb_russian": "тратить", "type_of_verb": "regular" },
    { "infinitive": "generalizar", "verb_russian": "обобщать", "type_of_verb": "regular" },
    { "infinitive": "glorificar", "verb_russian": "прославлять", "type_of_verb": "regular" },
    { "infinitive": "gobernar", "verb_russian": "управлять (руководить)", "type_of_verb": "irregular" },
    { "infinitive": "graduar", "verb_russian": "градуировать", "type_of_verb": "regular" },
    { "infinitive": "graduarse", "verb_russian": "окончить", "type_of_verb": "regular" },
    { "infinitive": "gritar", "verb_russian": "кричать", "type_of_verb": "regular" },
    { "infinitive": "gruñir", "verb_russian": "рычать", "type_of_verb": "regular" },
    { "infinitive": "guardar", "verb_russian": "сохранять, беречь, стеречь", "type_of_verb": "regular" },
    { "infinitive": "guiar", "verb_russian": "вести", "type_of_verb": "regular" },
    { "infinitive": "gustar", "verb_russian": "нравиться", "type_of_verb": "regular" },
    { "infinitive": "hablar", "verb_russian": "говорить", "type_of_verb": "regular" },
    { "infinitive": "hacer", "verb_russian": "делать", "type_of_verb": "irregular" },
    { "infinitive": "hallar", "verb_russian": "находить", "type_of_verb": "regular" },
    { "infinitive": "hallarse", "verb_russian": "находиться, бывать, заключаться", "type_of_verb": "regular" },
    { "infinitive": "helar", "verb_russian": "заморозить", "type_of_verb": "irregular" },
    { "infinitive": "heredar", "verb_russian": "наследовать", "type_of_verb": "regular" },
    { "infinitive": "herir", "verb_russian": "ранить", "type_of_verb": "irregular" },
    { "infinitive": "hervir", "verb_russian": "варить (кипятить)", "type_of_verb": "irregular" },
    { "infinitive": "huir", "verb_russian": "убегать", "type_of_verb": "regular" },
    { "infinitive": "ilustrar", "verb_russian": "проиллюстрировать", "type_of_verb": "regular" },
    { "infinitive": "importar", "verb_russian": "импортировать", "type_of_verb": "regular" },
    { "infinitive": "imprimir", "verb_russian": "печатать", "type_of_verb": "regular" },
    { "infinitive": "incluir", "verb_russian": "включать (содержать)", "type_of_verb": "regular" },
    { "infinitive": "indicar", "verb_russian": "указывать", "type_of_verb": "regular" },
    { "infinitive": "inducir", "verb_russian": "побудить", "type_of_verb": "irregular" },
    { "infinitive": "influir", "verb_russian": "влиять", "type_of_verb": "regular" },
    { "infinitive": "informar", "verb_russian": "сообщить", "type_of_verb": "regular" },
    { "infinitive": "iniciar", "verb_russian": "начинать (инициировать)", "type_of_verb": "regular" },
    { "infinitive": "inmigrar", "verb_russian": "иммигрировать", "type_of_verb": "regular" },
    { "infinitive": "insistir", "verb_russian": "настаивать", "type_of_verb": "regular" },
    { "infinitive": "instalar", "verb_russian": "установить", "type_of_verb": "regular" },
    { "infinitive": "insultar", "verb_russian": "оскорблять (обижать)", "type_of_verb": "regular" },
    { "infinitive": "intentar", "verb_russian": "пытаться", "type_of_verb": "regular" },
    { "infinitive": "interesar", "verb_russian": "интересовать", "type_of_verb": "regular" },
    { "infinitive": "interpretar", "verb_russian": "интерпретировать", "type_of_verb": "regular" },
    { "infinitive": "introducir", "verb_russian": "ввести", "type_of_verb": "irregular" },
    { "infinitive": "invadir", "verb_russian": "захватывать, оккупировать, вторгаться", "type_of_verb": "regular" },
    { "infinitive": "inventar", "verb_russian": "изобретать", "type_of_verb": "regular" },
    { "infinitive": "invertir", "verb_russian": "вкладывать (инвестировать)", "type_of_verb": "irregular" },
    { "infinitive": "investigar", "verb_russian": "расследовать", "type_of_verb": "regular" },
    { "infinitive": "invitar", "verb_russian": "приглашать", "type_of_verb": "regular" },
    { "infinitive": "invocar", "verb_russian": "вызывать", "type_of_verb": "regular" },
    { "infinitive": "ir", "verb_russian": "идти", "type_of_verb": "irregular" },
    { "infinitive": "irse", "verb_russian": "уйти, уходить, уезжать", "type_of_verb": "irregular" },
    { "infinitive": "jactarse", "verb_russian": "похваляться", "type_of_verb": "regular" },
    { "infinitive": "jugar", "verb_russian": "играть", "type_of_verb": "irregular" },
    { "infinitive": "juntar", "verb_russian": "собрать", "type_of_verb": "regular" },
    { "infinitive": "juntarse", "verb_russian": "собраться", "type_of_verb": "regular" },
    { "infinitive": "jurar", "verb_russian": "клясться", "type_of_verb": "regular" },
    { "infinitive": "ladrar", "verb_russian": "лаять", "type_of_verb": "regular" },
    { "infinitive": "lamentar", "verb_russian": "сожалеть", "type_of_verb": "regular" },
    { "infinitive": "lanzar", "verb_russian": "бросить (метать)", "type_of_verb": "regular" },
    { "infinitive": "lastimar", "verb_russian": "ранить (сожалеть)", "type_of_verb": "regular" },
    { "infinitive": "lavar", "verb_russian": "мыть, вымыть, умывать", "type_of_verb": "regular" },
    { "infinitive": "lavarse", "verb_russian": "помыться, умываться", "type_of_verb": "regular" },
    { "infinitive": "leer", "verb_russian": "читать", "type_of_verb": "regular" },
    { "infinitive": "legalizar", "verb_russian": "легализовать", "type_of_verb": "regular" },
    { "infinitive": "levantar", "verb_russian": "подниматься", "type_of_verb": "regular" },
    { "infinitive": "levantarse", "verb_russian": "вставать, подниматься, восходить", "type_of_verb": "regular" },
    { "infinitive": "limpiar", "verb_russian": "чистить", "type_of_verb": "regular" },
    { "infinitive": "llamar", "verb_russian": "звать", "type_of_verb": "regular" },
    { "infinitive": "llamarse", "verb_russian": "называться", "type_of_verb": "regular" },
    { "infinitive": "llegar", "verb_russian": "приходить (прибывать, приезжать)", "type_of_verb": "regular" },
    { "infinitive": "llenar", "verb_russian": "заполнять", "type_of_verb": "regular" },
    { "infinitive": "llevar", "verb_russian": "носить (нести, относить)", "type_of_verb": "regular" },
    { "infinitive": "llorar", "verb_russian": "плакать", "type_of_verb": "regular" },
    { "infinitive": "llover", "verb_russian": "идти (о дожде)", "type_of_verb": "irregular" },
    { "infinitive": "lograr", "verb_russian": "достигать, добиваться", "type_of_verb": "regular" },
    { "infinitive": "luchar", "verb_russian": "бороться", "type_of_verb": "regular" },
    { "infinitive": "madurar", "verb_russian": "повзрослеть", "type_of_verb": "regular" },
    { "infinitive": "mandar", "verb_russian": "приказывать", "type_of_verb": "regular" },
    { "infinitive": "manejar", "verb_russian": "управлять", "type_of_verb": "regular" },
    { "infinitive": "mantener", "verb_russian": "поддерживать", "type_of_verb": "irregular" },
    { "infinitive": "maquillar", "verb_russian": "делать макияж", "type_of_verb": "regular" },
    { "infinitive": "maquillarse", "verb_russian": "краситься, делать макияж", "type_of_verb": "regular" },
    { "infinitive": "marcar", "verb_russian": "отметить, пометить", "type_of_verb": "regular" },
    { "infinitive": "masticar", "verb_russian": "жевать", "type_of_verb": "regular" },
    { "infinitive": "matar", "verb_russian": "убивать", "type_of_verb": "regular" },
    { "infinitive": "matricular", "verb_russian": "зачислить, зарегистрировать", "type_of_verb": "regular" },
    { "infinitive": "matricularse", "verb_russian": "поступить, поступать, записываться", "type_of_verb": "regular" },
    { "infinitive": "medir", "verb_russian": "измерять (мерить)", "type_of_verb": "irregular" },
    { "infinitive": "mentir", "verb_russian": "врать", "type_of_verb": "irregular" },
    { "infinitive": "merecer", "verb_russian": "заслуживать", "type_of_verb": "irregular" },
    { "infinitive": "merendar", "verb_russian": "перекусывать", "type_of_verb": "irregular" },
    { "infinitive": "meter", "verb_russian": "засунуть, затолкать, заправить", "type_of_verb": "regular" },
    { "infinitive": "mezclar", "verb_russian": "мешать (перемешивать)", "type_of_verb": "regular" },
    { "infinitive": "mirar", "verb_russian": "смотреть", "type_of_verb": "regular" },
    { "infinitive": "modificar", "verb_russian": "изменить, модифицировать", "type_of_verb": "regular" },
    { "infinitive": "molestar", "verb_russian": "беспокоить", "type_of_verb": "regular" },
    { "infinitive": "montar", "verb_russian": "монтировать, устанавливать, собирать", "type_of_verb": "regular" },
    { "infinitive": "morir", "verb_russian": "умереть", "type_of_verb": "irregular" },
    { "infinitive": "mostrar", "verb_russian": "показывать", "type_of_verb": "irregular" },
    { "infinitive": "mover", "verb_russian": "двигать", "type_of_verb": "irregular" },
    { "infinitive": "moverse", "verb_russian": "двигаться", "type_of_verb": "irregular" },
    { "infinitive": "mudar", "verb_russian": "переехать, переезжать, переселять", "type_of_verb": "regular" },
    { "infinitive": "mudarse", "verb_russian": "переехать, переселяться", "type_of_verb": "regular" },
    { "infinitive": "nacer", "verb_russian": "родиться", "type_of_verb": "irregular" },
    { "infinitive": "nadar", "verb_russian": "плавать", "type_of_verb": "regular" },
    { "infinitive": "navegar", "verb_russian": "плыть", "type_of_verb": "regular" },
    { "infinitive": "necesitar", "verb_russian": "нуждаться", "type_of_verb": "regular" },
    { "infinitive": "negar", "verb_russian": "отказать (отрицать)", "type_of_verb": "irregular" },
    { "infinitive": "negarse", "verb_russian": "отказываться", "type_of_verb": "irregular" },
    { "infinitive": "negociar", "verb_russian": "вести переговоры", "type_of_verb": "regular" },
    { "infinitive": "nevar", "verb_russian": "идти (о снеге)", "type_of_verb": "irregular" },
    { "infinitive": "notar", "verb_russian": "уведомлять", "type_of_verb": "regular" },
    { "infinitive": "obedecer", "verb_russian": "повиноваться", "type_of_verb": "irregular" },
    { "infinitive": "obligar", "verb_russian": "заставлять (принуждать)", "type_of_verb": "regular" },
    { "infinitive": "obtener", "verb_russian": "получать (добиваться)", "type_of_verb": "irregular" },
    { "infinitive": "ocurrir", "verb_russian": "происходить (случаться)", "type_of_verb": "regular" },
    { "infinitive": "odiar", "verb_russian": "ненавидеть", "type_of_verb": "regular" },
    { "infinitive": "ofender", "verb_russian": "обидеть", "type_of_verb": "regular" },
    { "infinitive": "ofrecer", "verb_russian": "предлагать", "type_of_verb": "irregular" },
    { "infinitive": "oír", "verb_russian": "слышать", "type_of_verb": "irregular" },
    { "infinitive": "oler", "verb_russian": "пахнуть (нюхать)", "type_of_verb": "irregular" },
    { "infinitive": "olvidar", "verb_russian": "забывать", "type_of_verb": "regular" },
    { "infinitive": "olvidarse", "verb_russian": "забывать", "type_of_verb": "regular" },
    { "infinitive": "oponer", "verb_russian": "противостоять", "type_of_verb": "irregular" },
    { "infinitive": "oponerse", "verb_russian": "возражать", "type_of_verb": "irregular" },
    { "infinitive": "organizar", "verb_russian": "организовать", "type_of_verb": "regular" },
    { "infinitive": "padecer", "verb_russian": "страдать", "type_of_verb": "irregular" },
    { "infinitive": "pagar", "verb_russian": "платить", "type_of_verb": "regular" },
    { "infinitive": "parar", "verb_russian": "останавливать", "type_of_verb": "regular" },
    { "infinitive": "parecer", "verb_russian": "казаться", "type_of_verb": "irregular" },
    { "infinitive": "participar", "verb_russian": "учавствовать", "type_of_verb": "regular" },
    { "infinitive": "pasar", "verb_russian": "проходить", "type_of_verb": "regular" },
    { "infinitive": "patinar", "verb_russian": "кататься на коньках, скользить", "type_of_verb": "regular" },
    { "infinitive": "pedir", "verb_russian": "просить", "type_of_verb": "irregular" },
    { "infinitive": "pegar", "verb_russian": "вставить, вставлять", "type_of_verb": "regular" },
    { "infinitive": "peinar", "verb_russian": "причесать", "type_of_verb": "regular" },
    { "infinitive": "peinarse", "verb_russian": "расчесывать, причесываться", "type_of_verb": "regular" },
    { "infinitive": "pelear", "verb_russian": "драться", "type_of_verb": "regular" },
    { "infinitive": "pensar", "verb_russian": "думать", "type_of_verb": "irregular" },
    { "infinitive": "perder", "verb_russian": "терять", "type_of_verb": "irregular" },
    { "infinitive": "perdonar", "verb_russian": "прощать, извинять", "type_of_verb": "regular" },
    { "infinitive": "permanecer", "verb_russian": "оставаться", "type_of_verb": "irregular" },
    { "infinitive": "permitir", "verb_russian": "позволять", "type_of_verb": "regular" },
    { "infinitive": "perseguir", "verb_russian": "преследовать", "type_of_verb": "irregular" },
    { "infinitive": "pertenecer", "verb_russian": "принадлежать", "type_of_verb": "irregular" },
    { "infinitive": "pesar", "verb_russian": "весить", "type_of_verb": "regular" },
    { "infinitive": "pescar", "verb_russian": "рыбачить", "type_of_verb": "regular" },
    { "infinitive": "picar", "verb_russian": "ужалить", "type_of_verb": "regular" },
    { "infinitive": "pintar", "verb_russian": "окрасить, покрасить, рисовать", "type_of_verb": "regular" },
    { "infinitive": "planchar", "verb_russian": "гладить, утюжить", "type_of_verb": "regular" },
    { "infinitive": "plantar", "verb_russian": "посадить", "type_of_verb": "regular" },
    { "infinitive": "platicar", "verb_russian": "беседовать", "type_of_verb": "regular" },
    { "infinitive": "poder", "verb_russian": "мочь", "type_of_verb": "irregular" },
    { "infinitive": "poner", "verb_russian": "поместить (положить, надеть)", "type_of_verb": "irregular" },
    { "infinitive": "ponerse", "verb_russian": "связаться", "type_of_verb": "irregular" },
    { "infinitive": "practicar", "verb_russian": "практиковаться", "type_of_verb": "regular" },
    { "infinitive": "predecir", "verb_russian": "предсказывать", "type_of_verb": "irregular" },
    { "infinitive": "preferir", "verb_russian": "предпочитать", "type_of_verb": "irregular" },
    { "infinitive": "preguntar", "verb_russian": "спрашивать", "type_of_verb": "regular" },
    { "infinitive": "preguntarse", "verb_russian": "задаваться вопросом", "type_of_verb": "regular" },
    { "infinitive": "preparar", "verb_russian": "приготавливать (готовить)", "type_of_verb": "regular" },
    { "infinitive": "prepararse", "verb_russian": "готовиться", "type_of_verb": "regular" },
    { "infinitive": "presentar", "verb_russian": "представлять (знакомить)", "type_of_verb": "regular" },
    { "infinitive": "presentir", "verb_russian": "предвидеть", "type_of_verb": "irregular" },
    { "infinitive": "preservar", "verb_russian": "сохранять", "type_of_verb": "regular" },
    { "infinitive": "prever", "verb_russian": "предвидеть", "type_of_verb": "irregular" },
    { "infinitive": "probar", "verb_russian": "пробовать", "type_of_verb": "irregular" },
    { "infinitive": "producir", "verb_russian": "производить", "type_of_verb": "irregular" },
    { "infinitive": "prohibir", "verb_russian": "запрещать", "type_of_verb": "regular" },
    { "infinitive": "prometer", "verb_russian": "обещать", "type_of_verb": "regular" },
    { "infinitive": "proponer", "verb_russian": "предлагать", "type_of_verb": "irregular" },
    { "infinitive": "proseguir", "verb_russian": "преследовать", "type_of_verb": "irregular" },
    { "infinitive": "proteger", "verb_russian": "защищать", "type_of_verb": "regular" },
    { "infinitive": "protestar", "verb_russian": "протестовать", "type_of_verb": "regular" },
    { "infinitive": "provocar", "verb_russian": "провоцировать", "type_of_verb": "regular" },
    { "infinitive": "publicar", "verb_russian": "разместить", "type_of_verb": "regular" },
    { "infinitive": "purificar", "verb_russian": "очищать", "type_of_verb": "regular" },
    { "infinitive": "quebrar", "verb_russian": "ломать", "type_of_verb": "irregular" },
    { "infinitive": "quebrarse", "verb_russian": "сломать", "type_of_verb": "irregular" },
    { "infinitive": "quedar", "verb_russian": "оставаться (оставлять)", "type_of_verb": "regular" },
    { "infinitive": "quedarse", "verb_russian": "оставаться", "type_of_verb": "regular" },
    { "infinitive": "quejarse", "verb_russian": "жаловаться", "type_of_verb": "regular" },
    { "infinitive": "quemar", "verb_russian": "сгореть", "type_of_verb": "regular" },
    { "infinitive": "quemarse", "verb_russian": "гореть", "type_of_verb": "regular" },
    { "infinitive": "querer", "verb_russian": "хотеть", "type_of_verb": "irregular" },
    { "infinitive": "realizar", "verb_russian": "выполнять", "type_of_verb": "regular" },
    { "infinitive": "rechazar", "verb_russian": "отвергать (отказываться)", "type_of_verb": "regular" },
    { "infinitive": "recibir", "verb_russian": "получать", "type_of_verb": "regular" },
    { "infinitive": "reciclar", "verb_russian": "регенерировать, модернизировать", "type_of_verb": "regular" },
    { "infinitive": "recoger", "verb_russian": "собирать, забирать", "type_of_verb": "regular" },
    { "infinitive": "recomendar", "verb_russian": "рекомендовать", "type_of_verb": "irregular" },
    { "infinitive": "reconocer", "verb_russian": "признавать", "type_of_verb": "irregular" },
    { "infinitive": "recordar", "verb_russian": "запомнить", "type_of_verb": "irregular" },
    { "infinitive": "reducir", "verb_russian": "уменьшить (сократить)", "type_of_verb": "irregular" },
    { "infinitive": "regalar", "verb_russian": "подарить, дарить", "type_of_verb": "regular" },
    { "infinitive": "regar", "verb_russian": "поливать", "type_of_verb": "irregular" },
    { "infinitive": "regatear", "verb_russian": "торговаться", "type_of_verb": "regular" },
    { "infinitive": "regir", "verb_russian": "управлять", "type_of_verb": "irregular" },
    { "infinitive": "registrar", "verb_russian": "регистрировать", "type_of_verb": "regular" },
    { "infinitive": "registrarse", "verb_russian": "регистрироваться", "type_of_verb": "regular" },
    { "infinitive": "regresar", "verb_russian": "возвращаться", "type_of_verb": "regular" },
    { "infinitive": "regular", "verb_russian": "регулярный", "type_of_verb": "regular" },
    { "infinitive": "rehusar", "verb_russian": "отказываться", "type_of_verb": "regular" },
    { "infinitive": "reinar", "verb_russian": "царствовать", "type_of_verb": "regular" },
    { "infinitive": "reír", "verb_russian": "смеяться", "type_of_verb": "irregular" },
    { "infinitive": "renacer", "verb_russian": "возродиться", "type_of_verb": "irregular" },
    { "infinitive": "reñir", "verb_russian": "ссориться", "type_of_verb": "irregular" },
    { "infinitive": "renovar", "verb_russian": "обновлять", "type_of_verb": "irregular" },
    { "infinitive": "renunciar", "verb_russian": "отказываться", "type_of_verb": "regular" },
    { "infinitive": "reparar", "verb_russian": "ремонтировать, чинить", "type_of_verb": "regular" },
    { "infinitive": "repasar", "verb_russian": "повторить", "type_of_verb": "regular" },
    { "infinitive": "repetir", "verb_russian": "повторять", "type_of_verb": "irregular" },
    { "infinitive": "replicar", "verb_russian": "копировать", "type_of_verb": "regular" },
    { "infinitive": "reportar", "verb_russian": "сообщать", "type_of_verb": "regular" },
    { "infinitive": "requerir", "verb_russian": "требовать", "type_of_verb": "irregular" },
    { "infinitive": "reservar", "verb_russian": "бронировать", "type_of_verb": "regular" },
    { "infinitive": "resolver", "verb_russian": "устранить, решать, разрешать", "type_of_verb": "irregular" },
    { "infinitive": "respetar", "verb_russian": "уважать", "type_of_verb": "regular" },
    { "infinitive": "respirar", "verb_russian": "дышать", "type_of_verb": "regular" },
    { "infinitive": "responder", "verb_russian": "отвечать", "type_of_verb": "regular" },
    { "infinitive": "resultar", "verb_russian": "оказываться (получаться)", "type_of_verb": "regular" },
    { "infinitive": "revelar", "verb_russian": "раскрыть", "type_of_verb": "regular" },
    { "infinitive": "rezar", "verb_russian": "молиться", "type_of_verb": "regular" },
    { "infinitive": "robar", "verb_russian": "украсть", "type_of_verb": "regular" },
    { "infinitive": "rogar", "verb_russian": "просить (умолять)", "type_of_verb": "irregular" },
    { "infinitive": "romper", "verb_russian": "ломать", "type_of_verb": "irregular" },
    { "infinitive": "saber", "verb_russian": "знать", "type_of_verb": "irregular" },
    { "infinitive": "sacar", "verb_russian": "вынимать (извлекать)", "type_of_verb": "regular" },
    { "infinitive": "sacrificar", "verb_russian": "жертвовать", "type_of_verb": "regular" },
    { "infinitive": "sacudir", "verb_russian": "трясти", "type_of_verb": "regular" },
    { "infinitive": "salir", "verb_russian": "выходить", "type_of_verb": "irregular" },
    { "infinitive": "saltar", "verb_russian": "прыгать", "type_of_verb": "regular" },
    { "infinitive": "saludar", "verb_russian": "приветствовать", "type_of_verb": "regular" },
    { "infinitive": "salvar", "verb_russian": "спасать", "type_of_verb": "regular" },
    { "infinitive": "satirizar", "verb_russian": "высмеивать", "type_of_verb": "regular" },
    { "infinitive": "satisfacer", "verb_russian": "удовлетворять", "type_of_verb": "irregular" },
    { "infinitive": "secar", "verb_russian": "сушить (вытирать)", "type_of_verb": "regular" },
    { "infinitive": "secarse", "verb_russian": "высыхать", "type_of_verb": "regular" },
    { "infinitive": "seguir", "verb_russian": "следовать", "type_of_verb": "irregular" },
    { "infinitive": "señalar", "verb_russian": "отметить", "type_of_verb": "regular" },
    { "infinitive": "sentar", "verb_russian": "сидеть", "type_of_verb": "irregular" },
    { "infinitive": "sentarse", "verb_russian": "садиться", "type_of_verb": "irregular" },
    { "infinitive": "sentir", "verb_russian": "чувствовать", "type_of_verb": "irregular" },
    { "infinitive": "sentirse", "verb_russian": "Чувствовать", "type_of_verb": "irregular" },
    { "infinitive": "ser", "verb_russian": "быть", "type_of_verb": "irregular" },
    { "infinitive": "servir", "verb_russian": "служить", "type_of_verb": "irregular" },
    { "infinitive": "significar", "verb_russian": "означать", "type_of_verb": "regular" },
    { "infinitive": "simbolizar", "verb_russian": "символизировать", "type_of_verb": "regular" },
    { "infinitive": "situar", "verb_russian": "расположить", "type_of_verb": "regular" },
    { "infinitive": "sobrevivir", "verb_russian": "выживать", "type_of_verb": "regular" },
    { "infinitive": "soler", "verb_russian": "иметь обыкновение (привычку)", "type_of_verb": "irregular" },
    { "infinitive": "sonar", "verb_russian": "звенеть (звучать)", "type_of_verb": "irregular" },
    { "infinitive": "soñar", "verb_russian": "мечтать", "type_of_verb": "irregular" },
    { "infinitive": "sonreír", "verb_russian": "улыбаться", "type_of_verb": "irregular" },
    { "infinitive": "soportar", "verb_russian": "поддерживать", "type_of_verb": "regular" },
    { "infinitive": "sorprender", "verb_russian": "удивить", "type_of_verb": "regular" },
    { "infinitive": "subir", "verb_russian": "подниматься", "type_of_verb": "regular" },
    { "infinitive": "suceder", "verb_russian": "случаться", "type_of_verb": "regular" },
    { "infinitive": "sufrir", "verb_russian": "страдать", "type_of_verb": "regular" },
    { "infinitive": "sugerir", "verb_russian": "предлагать (внушать, намекать)", "type_of_verb": "irregular" },
    { "infinitive": "suponer", "verb_russian": "предполагать", "type_of_verb": "irregular" },
    { "infinitive": "surgir", "verb_russian": "возникнуть", "type_of_verb": "regular" },
    { "infinitive": "suspirar", "verb_russian": "вздыхать", "type_of_verb": "regular" },
    { "infinitive": "sustituir", "verb_russian": "заменять", "type_of_verb": "regular" },
    { "infinitive": "tañer", "verb_russian": "играть", "type_of_verb": "regular" },
    { "infinitive": "tapar", "verb_russian": "заткнуть", "type_of_verb": "regular" },
    { "infinitive": "tardar", "verb_russian": "задерживать", "type_of_verb": "regular" },
    { "infinitive": "temer", "verb_russian": "бояться", "type_of_verb": "regular" },
    { "infinitive": "tener", "verb_russian": "иметь", "type_of_verb": "irregular" },
    { "infinitive": "teñir", "verb_russian": "окрасить", "type_of_verb": "irregular" },
    { "infinitive": "terminar", "verb_russian": "заканчивать", "type_of_verb": "regular" },
    { "infinitive": "tirar", "verb_russian": "бросать", "type_of_verb": "regular" },
    { "infinitive": "tocar", "verb_russian": "трогать", "type_of_verb": "regular" },
    { "infinitive": "tomar", "verb_russian": "брать (взять, принимать)", "type_of_verb": "regular" },
    { "infinitive": "torcer", "verb_russian": "скручивать", "type_of_verb": "irregular" },
    { "infinitive": "toser", "verb_russian": "кашлять", "type_of_verb": "regular" },
    { "infinitive": "trabajar", "verb_russian": "работать", "type_of_verb": "regular" },
    { "infinitive": "traducir", "verb_russian": "переводить", "type_of_verb": "irregular" },
    { "infinitive": "traer", "verb_russian": "приносить", "type_of_verb": "irregular" },
    { "infinitive": "tragar", "verb_russian": "глотать", "type_of_verb": "regular" },
    { "infinitive": "tratar", "verb_russian": "пользоваться (общаться)", "type_of_verb": "regular" },
    { "infinitive": "triunfar", "verb_russian": "преуспевать", "type_of_verb": "regular" },
    { "infinitive": "tropezar", "verb_russian": "спотыкаться", "type_of_verb": "irregular" },
    { "infinitive": "ubicar", "verb_russian": "расположить", "type_of_verb": "regular" },
    { "infinitive": "unir", "verb_russian": "соединить (составить)", "type_of_verb": "regular" },
    { "infinitive": "untar", "verb_russian": "распространять", "type_of_verb": "regular" },
    { "infinitive": "usar", "verb_russian": "использовать (употреблять)", "type_of_verb": "regular" },
    { "infinitive": "utilizar", "verb_russian": "использовать", "type_of_verb": "regular" },
    { "infinitive": "vaciar", "verb_russian": "опустошить, опорожнить", "type_of_verb": "regular" },
    { "infinitive": "valer", "verb_russian": "стоить (ценить)", "type_of_verb": "irregular" },
    { "infinitive": "variar", "verb_russian": "менять", "type_of_verb": "regular" },
    { "infinitive": "vencer", "verb_russian": "побеждать (выигрывать)", "type_of_verb": "regular" },
    { "infinitive": "vender", "verb_russian": "продавать", "type_of_verb": "regular" },
    { "infinitive": "venir", "verb_russian": "приезжать", "type_of_verb": "irregular" },
    { "infinitive": "ver", "verb_russian": "видеть (смотреть)", "type_of_verb": "irregular" },
    { "infinitive": "verificar", "verb_russian": "проверить, подтверждать, сверить", "type_of_verb": "regular" },
    { "infinitive": "vestir", "verb_russian": "одевать", "type_of_verb": "irregular" },
    { "infinitive": "vestirse", "verb_russian": "одеваться", "type_of_verb": "irregular" },
    { "infinitive": "viajar", "verb_russian": "путешествовать", "type_of_verb": "regular" },
    { "infinitive": "violar", "verb_russian": "нарушать, посягать", "type_of_verb": "regular" },
    { "infinitive": "visitar", "verb_russian": "посещать", "type_of_verb": "regular" },
    { "infinitive": "vivir", "verb_russian": "жить", "type_of_verb": "regular" },
    { "infinitive": "volar", "verb_russian": "летать", "type_of_verb": "irregular" },
    { "infinitive": "volver", "verb_russian": "возвращаться (вернуть)", "type_of_verb": "irregular" },
    { "infinitive": "vomitar", "verb_russian": "извергать, тошнить", "type_of_verb": "regular" },
    { "infinitive": "votar", "verb_russian": "голосовать", "type_of_verb": "regular" },
    { "infinitive": "yacer", "verb_russian": "лежать, почивать", "type_of_verb": "irregular" },
    { "infinitive": "zambullirse", "verb_russian": "нырять, погружаться, окунаться", "type_of_verb": "regular" }
]